export type { CalendarLanguage } from './model';
const HINT_COPY = {
  fr: {"hint": "Indice", "solving": "Recherche d’une solution…", "hintPlace": "Placez la pièce lumineuse dans son contour", "hintAdjust": "Autre solution : déplacez la pièce lumineuse", "hintUnavailable": "Indice indisponible. Réessayez", "hintNone": "Aucune solution pour cette date"},
  de: {"hint": "Hinweis", "solving": "Lösung wird gesucht…", "hintPlace": "Lege das leuchtende Teil in seinen Umriss", "hintAdjust": "Andere Lösung: Versetze das leuchtende Teil", "hintUnavailable": "Kein Hinweis verfügbar. Erneut versuchen", "hintNone": "Keine Lösung für dieses Datum"},
  es: {"hint": "Pista", "solving": "Buscando una solución…", "hintPlace": "Coloca la pieza brillante en su contorno", "hintAdjust": "Otra solución: mueve la pieza brillante", "hintUnavailable": "Pista no disponible. Inténtalo de nuevo", "hintNone": "No hay solución para esta fecha"},

  zh: { hint: '提示', solving: '正在寻找可行的拼法…', hintPlace: '将闪烁拼块放入同色轮廓，可旋转或翻转', hintAdjust: '参考另一种拼法，请调整高亮拼块', hintUnavailable: '暂未找到解，请稍后再试', hintNone: '这个日期暂无可用解' },
  en: { hint: 'Hint', solving: 'Finding a solution…', hintPlace: 'Match the glowing piece to its outline; rotate or flip', hintAdjust: 'Try this solution. Reposition the glowing piece', hintUnavailable: 'No hint yet. Please try again', hintNone: 'No solution for this date' },
  ja: { hint: 'ヒント', solving: '解き方を探しています…', hintPlace: '光るピースを同じ色の枠へ。回転・反転もできます', hintAdjust: '別の解き方です。光るピースを移動', hintUnavailable: 'ヒントを取得できません。もう一度お試しください', hintNone: 'この日付の解が見つかりません' },
} as const;
const BASE_COPY = {
  fr: {"calendar": "Calendrier", "history": "Historique", "cleared": "Terminés", "chooseDate": "Choisissez une date pour jouer", "back": "Retour au puzzle", "viewHistory": "Voir les réussites", "continue": "Continuer", "recorded": "Une journée de plus !", "total": "Jours terminés", "title": "Puzzle du calendrier", "tray": "PIÈCES", "help": "Laissez libres le mois, la date et le jour", "rotate": "Tourner", "flip": "Retourner", "reset": "Mélanger", "settings": "Paramètres", "month": "Mois", "day": "Date", "weekday": "Jour", "language": "Langue", "today": "Aujourd’hui", "done": "Terminé", "won": "Puzzle terminé !", "progress": "Placées", "months": ["Jan", "Fév", "Mar", "Avr", "Mai", "Juin", "Juil", "Août", "Sep", "Oct", "Nov", "Déc"], "weekdays": ["Dim", "Lun", "Mar", "Mer", "Jeu", "Ven", "Sam"]},
  de: {"calendar": "Kalender", "history": "Erfolge", "cleared": "Gelöst", "chooseDate": "Wähle ein Datum für dein Puzzle", "back": "Zurück zum Puzzle", "viewHistory": "Erfolge ansehen", "continue": "Weiter", "recorded": "Ein weiterer Tag geschafft!", "total": "Gelöste Tage", "title": "Kalenderpuzzle", "tray": "TEILE", "help": "Monat, Datum und Wochentag frei lassen", "rotate": "Drehen", "flip": "Spiegeln", "reset": "Mischen", "settings": "Einstellungen", "month": "Monat", "day": "Datum", "weekday": "Wochentag", "language": "Sprache", "today": "Heute", "done": "Fertig", "won": "Puzzle gelöst!", "progress": "Gelegt", "months": ["Jan", "Feb", "Mär", "Apr", "Mai", "Jun", "Jul", "Aug", "Sep", "Okt", "Nov", "Dez"], "weekdays": ["So", "Mo", "Di", "Mi", "Do", "Fr", "Sa"]},
  es: {"calendar": "Calendario", "history": "Historial", "cleared": "Completados", "chooseDate": "Elige una fecha para jugar", "back": "Volver al puzle", "viewHistory": "Ver historial", "continue": "Continuar", "recorded": "¡Otro día completado!", "total": "Días completados", "title": "Puzle del calendario", "tray": "PIEZAS", "help": "Deja libres el mes, la fecha y el día", "rotate": "Girar", "flip": "Voltear", "reset": "Mezclar", "settings": "Ajustes", "month": "Mes", "day": "Fecha", "weekday": "Día", "language": "Idioma", "today": "Hoy", "done": "Listo", "won": "¡Puzle completado!", "progress": "Colocadas", "months": ["Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic"], "weekdays": ["Dom", "Lun", "Mar", "Mié", "Jue", "Vie", "Sáb"]},

  zh: { calendar: '万年历', history: '通关记录', cleared: '已通关', chooseDate: '选择日期，开始新的挑战', back: '返回拼图', viewHistory: '查看记录', continue: '继续', recorded: '这一天已点亮！', total: '累计通关', title: '日历拼图', tray: '拼图块', help: '空出所选月份、日期和星期', rotate: '旋转', flip: '翻转', reset: '打乱', settings: '设置', month: '月份', day: '日期', weekday: '星期', language: '语言', today: '今天', done: '完成', won: '拼图完成！', progress: '已放置', months: ['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'], weekdays: ['周日','周一','周二','周三','周四','周五','周六'] },
  en: { calendar: 'Calendar', history: 'History', cleared: 'Completed', chooseDate: 'Pick a date for your next puzzle', back: 'Back to puzzle', viewHistory: 'View history', continue: 'Continue', recorded: 'Another day completed!', total: 'Days completed', title: 'Calendar Puzzle', tray: 'PIECES', help: 'Leave the month, date and weekday uncovered', rotate: 'Rotate', flip: 'Flip', reset: 'Shuffle', settings: 'Settings', month: 'Month', day: 'Date', weekday: 'Weekday', language: 'Language', today: 'Today', done: 'Done', won: 'Puzzle complete!', progress: 'Placed', months: ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'], weekdays: ['Sun','Mon','Tue','Wed','Thu','Fri','Sat'] },
  ja: { calendar: 'カレンダー', history: 'クリア記録', cleared: 'クリア済み', chooseDate: '日付を選んで挑戦しよう', back: 'パズルに戻る', viewHistory: '記録を見る', continue: '続ける', recorded: 'この日をクリア！', total: 'クリア日数', title: 'カレンダーパズル', tray: 'ピース', help: '月・日・曜日のマスを残そう', rotate: '回転', flip: '反転', reset: 'シャッフル', settings: '設定', month: '月', day: '日', weekday: '曜日', language: '言語', today: '今日', done: '完了', won: 'パズル完成！', progress: '配置', months: ['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'], weekdays: ['日曜','月曜','火曜','水曜','木曜','金曜','土曜'] },
} as const;
export const CALENDAR_COPY = { fr: { ...BASE_COPY.fr, ...HINT_COPY.fr }, de: { ...BASE_COPY.de, ...HINT_COPY.de }, es: { ...BASE_COPY.es, ...HINT_COPY.es }, zh: { ...BASE_COPY.zh, ...HINT_COPY.zh }, en: { ...BASE_COPY.en, ...HINT_COPY.en }, ja: { ...BASE_COPY.ja, ...HINT_COPY.ja } };
export const CALENDAR_GLYPHS = [...new Set(Array.from(JSON.stringify(CALENDAR_COPY) + '中文 English 日本語 ⚙ × ‹ › « » ▦ ✓ ★ 0123456789 / · -'))].join('');
