import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { registerHooks } from 'node:module';
import test from 'node:test';

registerHooks({ resolve(specifier, context, nextResolve) { const relativeWithoutExtension = /^\.{1,2}\//u.test(specifier) && !/\.[a-z0-9]+$/iu.test(specifier); return nextResolve(relativeWithoutExtension ? `${specifier}.ts` : specifier, context); } });
const [{ createMugenVfs }, { importMugenCharacter }, { createMugenCharacterModel }, { MugenInputHistory }, { MugenHeadlessMatch }, { MugenScriptRuntime }, { MugenCombatRuntime }, { validateMugenStageFixture }] = await Promise.all([import('../mugen/import/vfs/MugenVfs.ts'), import('../mugen/import/worker/MugenCharacterImport.ts'), import('../mugen/viewer/MugenCharacterModel.ts'), import('../mugen/runtime/input/index.ts'), import('../mugen/runtime/match/index.ts'), import('../mugen/runtime/script/index.ts'), import('../mugen/runtime/combat/index.ts'), import('../mugen/game/MugenStageFixture.ts')]);
const CONTROLS = Object.freeze(['up', 'down', 'left', 'right', 'a', 'b', 'c', 'x', 'y', 'z', 'start']);
const SOAK_MATCHES = Number(process.env.MUGEN_G08_SOAK_MATCHES ?? 1_000);
if (!Number.isSafeInteger(SOAK_MATCHES) || SOAK_MATCHES < 1 || SOAK_MATCHES > 10_000) throw new RangeError('MUGEN_G08_SOAK_MATCHES must be from 1 to 10000.');

test('G08-E owns two distinct licensed character packages and one deterministic stage fixture', async () => {
  const [fighter, rival] = await Promise.all([load('fighter'), load('rival')]); const rivalManifest = JSON.parse(read('../mugen/fixtures/g08-rival-v1.fixture.json')); const stageManifest = JSON.parse(read('../mugen/fixtures/g08-stage-v1.fixture.json')); const stageBytes = readBytes('../mugen/fixtures/g08-stage-v1/stage.json'); const stage = validateMugenStageFixture(JSON.parse(new TextDecoder().decode(stageBytes)));
  assert.notEqual(fighter.encoded.packageSha256, rival.encoded.packageSha256); assert.equal(rival.encoded.packageSha256, rivalManifest.expected.packageSha256); assert.equal(fighter.metadata.name, 'Haiyue Fighter'); assert.equal(rival.metadata.name, 'Haiyue Rival'); assert.equal(fighter.package.tables.sounds.length, 6); assert.equal(rival.package.tables.sounds.length, 6); assert.equal(stage.id, 'haiyue-night-grid'); assert.deepEqual({ bytes: stageBytes.byteLength, sha256: sha(stageBytes) }, stageManifest.files['stage.json']);
  for (const [name, expected] of Object.entries(rivalManifest.files)) { const bytes = readBytes(`../mugen/fixtures/g08-rival-v1/${name}`); assert.deepEqual({ bytes: bytes.byteLength, sha256: sha(bytes) }, expected); }
});

test('G08-E two-package match reaches KO/win, emits ordered audio and replays byte-exact after restart', async () => {
  const [fighter, rival] = await Promise.all([load('fighter'), load('rival')]); const first = runMatch(fighter, rival); const second = runMatch(fighter, rival);
  assert.equal(first.final.phase, 'match-over'); assert.equal(first.final.matchWinnerId, 'P1'); assert.equal(first.final.fighters[1].packageSha256, rival.encoded.packageSha256); assert(first.audio.some(value => value.operation === 'play' && value.group === 2)); assert(first.audio.some(value => value.operation === 'stop')); assert(first.contacts >= 12); assert.deepEqual(first.traceHashes, second.traceHashes); assert.equal(first.final.hash, second.final.hash); assert.equal(first.eventDigest, second.eventDigest); assert(first.ticks < 2_000);
  if (process.env.MUGEN_EVIDENCE === '1') console.log(JSON.stringify({ evidenceRole: 'g08e-complete-match', ticks: first.ticks, finalStateSha256: first.final.hash, stateTraceSha256: sha(new TextEncoder().encode(JSON.stringify(first.traceHashes))), eventTraceSha256: first.eventDigest, contacts: first.contacts }));
});

test(`G08-E replays the same complete short match ${SOAK_MATCHES} times without trace drift`, async () => {
  const [fighter, rival] = await Promise.all([load('fighter'), load('rival')]);
  const baseline = runMatch(fighter, rival, { maxLife: 90, maxTicks: 200 });
  assert.equal(baseline.final.phase, 'match-over');
  for (let replay = 0; replay < SOAK_MATCHES; replay += 1) {
    const candidate = runMatch(fighter, rival, { maxLife: 90, maxTicks: 200 });
    assert.deepEqual(candidate.traceHashes, baseline.traceHashes, `state trace drifted at replay ${replay}`);
    assert.equal(candidate.eventDigest, baseline.eventDigest, `event trace drifted at replay ${replay}`);
    assert.equal(candidate.final.hash, baseline.final.hash, `final state drifted at replay ${replay}`);
  }
  if (process.env.MUGEN_EVIDENCE === '1') console.log(JSON.stringify({ evidenceRole: 'g08e-match-replay-soak', replays: SOAK_MATCHES, ticksPerReplay: baseline.ticks, finalStateSha256: baseline.final.hash, stateTraceSha256: sha(new TextEncoder().encode(JSON.stringify(baseline.traceHashes))), eventTraceSha256: baseline.eventDigest }));
});

function runMatch(fighter, rival, options = {}) { const a = runtime(fighter, 'hero.air'); const b = runtime(rival, 'rival.air'); const maxLife = options.maxLife ?? 1_000; const maxTicks = options.maxTicks ?? 2_000; const match = new MugenHeadlessMatch({ seed: 'm08-g08-stage-v1', roundsToWin: 1, roundTimeTicks: 5_940, fighters: [{ id: 'P1', displayName: 'Haiyue Fighter', packageSha256: fighter.encoded.packageSha256, spawn: [-14, 0], facing: 1, initialControl: true, maxLife }, { id: 'P2', displayName: 'Haiyue Rival', packageSha256: rival.encoded.packageSha256, spawn: [14, 0], facing: -1, initialControl: true, maxLife }] }); const script = new MugenScriptRuntime([{ fighterId: 'P1', commands: a.commands, states: a.states }, { fighterId: 'P2', commands: b.commands, states: b.states }]); const combat = new MugenCombatRuntime(script, { fighters: [{ fighterId: 'P1', air: a.air }, { fighterId: 'P2', air: b.air }], stageBounds: [-145, 145], guardDistance: 72, koHoldTicks: 2 }); const inputs = inputBuilder(match); const traceHashes = []; const events = []; let contacts = 0; let sendAttack = true; let result;
  for (let index = 0; index < maxTicks; index++) { const before = match.snapshot(); const p1 = before.fighters[0]; const p2 = before.fighters[1]; const distance = Math.abs(p2.position[0] - p1.position[0]); const chase = before.phase === 'fight' && p1.control && distance > 26 ? (p2.position[0] > p1.position[0] ? 'right' : 'left') : null; const attack = before.phase === 'fight' && p1.control && p1.stateNumber === 0 && chase === null && sendAttack; const held = chase === null ? attack ? { P1: ['x'] } : {} : { P1: [chase] }; sendAttack = !attack; const input = inputs.push(held); match.beginTick(input); if (before.phase === 'ready') match.startFight(); const combatTrace = combat.step(match, input, inputs.history); contacts += combatTrace.contacts.length; result = match.endTick(); traceHashes.push(result.traceHash); events.push(...result.events); if (result.state.phase === 'match-over') break; }
  assert(result); const audio = events.filter(value => value.kind === 'audio'); return { final: result.state, traceHashes, audio, contacts, ticks: result.state.tick, eventDigest: sha(new TextEncoder().encode(JSON.stringify(events))) };
}
function runtime(imported, airPath) { const model = createMugenCharacterModel(imported.package, imported.metadata); return { commands: imported.package.tables.commands[0], states: imported.package.tables.states[0], air: Object.freeze({ canonicalPath: airPath, sourceSha256: imported.package.sourceSetSha256, actions: Object.freeze(model.actions.map(value => value.action)), diagnostics: model.diagnostics, elementCount: model.actions.reduce((sum, value) => sum + value.action.elements.length, 0), collisionBoxCount: model.actions.reduce((sum, value) => sum + value.clsn1Count + value.clsn2Count, 0) }) }; }
async function load(kind) { const paths = kind === 'fighter' ? ['hero.def', 'hero.cmd', 'hero.cns', 'hero.air', 'hero.sff', 'hero.act', 'vertical.snd'] : ['rival.def', 'rival.cmd', 'rival.cns', 'rival.air', 'rival.sff', 'rival.act', 'rival.snd']; const inputs = paths.map(path => ({ path, bytes: kind === 'fighter' ? path === 'hero.sff' || path === 'hero.act' ? readBytes(`../mugen/fixtures/g05-viewer-v1/${path}`) : path === 'vertical.snd' ? readBytes('../mugen/fixtures/g06-generated-snd-v1/vertical.snd') : readBytes(`../mugen/fixtures/g08-game-v1/${path}`) : readBytes(`../mugen/fixtures/g08-rival-v1/${path}`) })); return importMugenCharacter(await createMugenVfs(inputs), { contentRole: 'formal-fixture', entryDef: paths[0], entryKind: 'character', encoding: 'utf-8', scriptProfile: 'g08-minimal' }); }
function inputBuilder(match) { const history = new MugenInputHistory(180); const previous = new Map([['P1', new Set()], ['P2', new Set()]]); return { history, push(values) { const players = ['P1', 'P2'].map(id => { const held = new Set(values[id] ?? []); const prior = previous.get(id); previous.set(id, held); return { id, actions: CONTROLS.map(action => ({ action, value: held.has(action) ? 1 : 0, held: held.has(action), pressed: held.has(action) && !prior.has(action), released: !held.has(action) && prior.has(action) })) }; }); const facing = Object.fromEntries(match.snapshot().fighters.map(value => [value.id, value.facing])); return history.push({ tick: history.tick + 1, players }, facing); } }; }
function read(path) { return readFileSync(new URL(path, import.meta.url), 'utf8'); }
function readBytes(path) { return new Uint8Array(readFileSync(new URL(path, import.meta.url))); }
function sha(bytes) { return createHash('sha256').update(bytes).digest('hex'); }
